name: python tests

on:
  push:
    branches:
      -main
    
jobs:
  testes:
      runs-on: ubuntu-latest
 steps:
  
- name: baixar codigo
  uses: actions/checkout@v4
  
- name: Instalar Python
  uses: actions/setup-python@v5
  with:
      python-version: '3.11'

- name: instalar pytest
  run: pip install pytest
  
- name: executar testes
  run: pytest
  
